# Generated by Django 4.2.1 on 2023-05-14 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InfoEmployee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=20)),
                ('position_occupied', models.CharField(max_length=20)),
                ('salary', models.IntegerField()),
                ('symbols_money', models.CharField(choices=[('$', 'dollar'), ('€', 'euro'), ('RON', 'ron')], default='RON', max_length=3)),
            ],
        ),
    ]
