# Generated by Django 4.2.1 on 2023-05-14 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='infoemployee',
            options={'verbose_name_plural': 'InfoEmployee'},
        ),
    ]
