# Generated by Django 4.2.1 on 2023-05-14 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0002_alter_infoemployee_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infoemployee',
            name='symbols_money',
            field=models.CharField(choices=[('', '$'), ('', '€'), ('', 'ron')], default='', max_length=1),
        ),
    ]
