# Generated by Django 4.2.1 on 2023-05-14 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0003_alter_infoemployee_symbols_money'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InfoEmployee',
            new_name='RegisterEmployee',
        ),
    ]
