# Generated by Django 4.2.1 on 2023-05-14 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0004_rename_infoemployee_registeremployee'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registeremployee',
            options={'verbose_name_plural': 'Register members'},
        ),
        migrations.AlterField(
            model_name='registeremployee',
            name='position_occupied',
            field=models.CharField(max_length=80),
        ),
    ]
