# Generated by Django 4.2.1 on 2023-05-14 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0005_alter_registeremployee_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeremployee',
            name='symbols_money',
            field=models.CharField(choices=[('', '$'), ('', '€'), ('', 'ron')], default='', max_length=3),
        ),
    ]
