# Generated by Django 4.2.1 on 2023-05-14 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0007_alter_registeremployee_symbols_money'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeremployee',
            name='symbols_money',
            field=models.CharField(choices=[('DOLLAR', '$'), ('EURO', '€'), ('RON', 'ron')], max_length=200),
        ),
    ]
