# Generated by Django 4.2.1 on 2023-05-14 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0008_alter_registeremployee_symbols_money'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registeremployee',
            name='salary',
            field=models.IntegerField(default=False),
        ),
    ]
